/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cyber.gltf --transform
Author: Blue Lantern (https://sketchfab.com/genoris2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-laptop-8330c89e8431451db3aa9d15c5836ddf
Title: CyberPunk Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cyber-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.025']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.028']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.027']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.029']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.031']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.038']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.036']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.039']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.012']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.018']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.019']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.020']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.014']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Material.015']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.021']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Material.022']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.023']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials['Material.034']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.032']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['Material.033']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Material.004']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Material.006']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.005']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cyber-transformed.glb')
