/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 img.gltf --transform
Author: Alexandr Zhilkin (https://sketchfab.com/allexandr007)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/helmet-06-5558d51af74a488f824976305acdf011
Title: Helmet 06
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/img-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.H06_00_B03_0.geometry} material={materials.material} position={[0, 0.038, -0.046]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
      <mesh geometry={nodes.H06_01_B01_0.geometry} material={materials.material_1} position={[0, 0.042, -0.046]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
      <mesh geometry={nodes.H06_02_b05_0.geometry} material={materials.material_2} position={[0.021, 0.13, -0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.H06_03_b04_0.geometry} material={materials.material_3} position={[0.021, 0.132, -0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.H06_04_b04_0.geometry} material={materials.material_3} position={[-0.004, 0.014, -0.017]} rotation={[1.745, 0, Math.PI]} scale={0.005} />
      <mesh geometry={nodes.H06_05_mat_H06_0.geometry} material={materials.mat_H06} position={[-1.118, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
      <mesh geometry={nodes.H06_007_B02_0.geometry} material={materials.material_5} position={[-1.118, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/img-transformed.glb')
